[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
headless = true
port = 8501
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
